//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_items
    {
        public int id { get; set; }
        public string catergory_id { get; set; }
        public string categoryName { get; set; }
        public Nullable<System.DateTime> categoryDcd { get; set; }
        public Nullable<System.DateTime> categoryEdd { get; set; }
    
        public virtual product_items product_items { get; set; }
    }
}
