//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEntity.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_items
    {
        public int id { get; set; }
        public string product_id { get; set; }
        public string catergory_id { get; set; }
        public string productName { get; set; }
        public string productDescription { get; set; }
        public Nullable<System.DateTime> productDcd { get; set; }
        public Nullable<System.DateTime> productEdd { get; set; }
    
        public virtual category_items category_items { get; set; }
    }
}
