//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiEntity.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class serverEntity : DbContext
    {
        public serverEntity()
            : base("name=serverEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MVC5> MVC5 { get; set; }
    
        public virtual ObjectResult<getUsertoEdit_Result1> getUsertoEdit(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<getUsertoEdit_Result1>("getUsertoEdit", idParameter);
        }
    
        public virtual ObjectResult<SelectUser_Result1> SelectUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SelectUser_Result1>("SelectUser");
        }
    }
}
